/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DoItWhereInput } from "./DoItWhereInput";
import { Type } from "class-transformer";
import { DoItOrderByInput } from "./DoItOrderByInput";

@ArgsType()
class DoItFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => DoItWhereInput,
  })
  @Field(() => DoItWhereInput, { nullable: true })
  @Type(() => DoItWhereInput)
  where?: DoItWhereInput;

  @ApiProperty({
    required: false,
    type: DoItOrderByInput,
  })
  @Field(() => DoItOrderByInput, { nullable: true })
  @Type(() => DoItOrderByInput)
  orderBy?: DoItOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { DoItFindManyArgs };
