/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateDoItArgs } from "./CreateDoItArgs";
import { UpdateDoItArgs } from "./UpdateDoItArgs";
import { DeleteDoItArgs } from "./DeleteDoItArgs";
import { DoItFindManyArgs } from "./DoItFindManyArgs";
import { DoItFindUniqueArgs } from "./DoItFindUniqueArgs";
import { DoIt } from "./DoIt";
import { DidItFindManyArgs } from "../../didIt/base/DidItFindManyArgs";
import { DidIt } from "../../didIt/base/DidIt";
import { DoItService } from "../doIt.service";

@graphql.Resolver(() => DoIt)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DoItResolverBase {
  constructor(
    protected readonly service: DoItService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DoIt",
    action: "read",
    possession: "any",
  })
  async _doItsMeta(
    @graphql.Args() args: DoItFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [DoIt])
  @nestAccessControl.UseRoles({
    resource: "DoIt",
    action: "read",
    possession: "any",
  })
  async doIts(
    @graphql.Args() args: DoItFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DoIt[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DoIt",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => DoIt, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DoIt",
    action: "read",
    possession: "own",
  })
  async doIt(
    @graphql.Args() args: DoItFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DoIt | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "DoIt",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => DoIt)
  @nestAccessControl.UseRoles({
    resource: "DoIt",
    action: "create",
    possession: "any",
  })
  async createDoIt(
    @graphql.Args() args: CreateDoItArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DoIt> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "DoIt",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DoIt"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => DoIt)
  @nestAccessControl.UseRoles({
    resource: "DoIt",
    action: "update",
    possession: "any",
  })
  async updateDoIt(
    @graphql.Args() args: UpdateDoItArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DoIt | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "DoIt",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DoIt"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DoIt)
  @nestAccessControl.UseRoles({
    resource: "DoIt",
    action: "delete",
    possession: "any",
  })
  async deleteDoIt(@graphql.Args() args: DeleteDoItArgs): Promise<DoIt | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DidIt])
  @nestAccessControl.UseRoles({
    resource: "DoIt",
    action: "read",
    possession: "any",
  })
  async didIts(
    @graphql.Parent() parent: DoIt,
    @graphql.Args() args: DidItFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DidIt[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DidIt",
    });
    const results = await this.service.findDidIts(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
