/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateDidItArgs } from "./CreateDidItArgs";
import { UpdateDidItArgs } from "./UpdateDidItArgs";
import { DeleteDidItArgs } from "./DeleteDidItArgs";
import { DidItFindManyArgs } from "./DidItFindManyArgs";
import { DidItFindUniqueArgs } from "./DidItFindUniqueArgs";
import { DidIt } from "./DidIt";
import { DoIt } from "../../doIt/base/DoIt";
import { DidItService } from "../didIt.service";

@graphql.Resolver(() => DidIt)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DidItResolverBase {
  constructor(
    protected readonly service: DidItService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DidIt",
    action: "read",
    possession: "any",
  })
  async _didItsMeta(
    @graphql.Args() args: DidItFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [DidIt])
  @nestAccessControl.UseRoles({
    resource: "DidIt",
    action: "read",
    possession: "any",
  })
  async didIts(
    @graphql.Args() args: DidItFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DidIt[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DidIt",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => DidIt, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DidIt",
    action: "read",
    possession: "own",
  })
  async didIt(
    @graphql.Args() args: DidItFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DidIt | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "DidIt",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => DidIt)
  @nestAccessControl.UseRoles({
    resource: "DidIt",
    action: "create",
    possession: "any",
  })
  async createDidIt(
    @graphql.Args() args: CreateDidItArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DidIt> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "DidIt",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DidIt"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        doit: args.data.doit
          ? {
              connect: args.data.doit,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => DidIt)
  @nestAccessControl.UseRoles({
    resource: "DidIt",
    action: "update",
    possession: "any",
  })
  async updateDidIt(
    @graphql.Args() args: UpdateDidItArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DidIt | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "DidIt",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DidIt"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          doit: args.data.doit
            ? {
                connect: args.data.doit,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DidIt)
  @nestAccessControl.UseRoles({
    resource: "DidIt",
    action: "delete",
    possession: "any",
  })
  async deleteDidIt(
    @graphql.Args() args: DeleteDidItArgs
  ): Promise<DidIt | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => DoIt, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DidIt",
    action: "read",
    possession: "any",
  })
  async doit(
    @graphql.Parent() parent: DidIt,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DoIt | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DoIt",
    });
    const result = await this.service.getDoit(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
