/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DidItWhereInput } from "./DidItWhereInput";
import { Type } from "class-transformer";
import { DidItOrderByInput } from "./DidItOrderByInput";

@ArgsType()
class DidItFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => DidItWhereInput,
  })
  @Field(() => DidItWhereInput, { nullable: true })
  @Type(() => DidItWhereInput)
  where?: DidItWhereInput;

  @ApiProperty({
    required: false,
    type: DidItOrderByInput,
  })
  @Field(() => DidItOrderByInput, { nullable: true })
  @Type(() => DidItOrderByInput)
  orderBy?: DidItOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { DidItFindManyArgs };
