/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DoItWhereUniqueInput } from "../../doIt/base/DoItWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
@InputType()
class DidItUpdateInput {
  @ApiProperty({
    required: false,
    type: () => DoItWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DoItWhereUniqueInput)
  @IsOptional()
  @Field(() => DoItWhereUniqueInput, {
    nullable: true,
  })
  doit?: DoItWhereUniqueInput | null;
}
export { DidItUpdateInput };
